version: "3.8"

services:
  public-service:
    build: ./public-service
    command: npm run start:dev
    volumes:
      - ./public-service:/app
      - ./app/node_modules
    env_file:
      - ./public-service/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - subscription-service
    restart: always

  subscription-service:
    build: ./subscription-service
    command: npm run start:dev
    volumes:
      - ./subscription-service:/app
      - ./app/node_modules
    env_file:
      - ./subscription-service/.env
    environment:
      DB_HOST: db
    ports:
      - "3001:3001"
    depends_on:
      - db
    restart: always

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: subscription
      POSTGRES_DB: subscription
    ports:
      - "5432:5432"
    volumes:
      - db-data:/data/postgres
    restart: unless-stopped

volumes:
  db-data:
